### ISSUE TITLE
No module named 'click'

### ISSUE THREAD

**Issue by dabeans** [tp7309/TTPassGen#2]
Getting this error.

C:\>C:\Windows\py.exe C:\TTPassGen-master\ttpassgen\ttpassgen.py
Traceback (most recent call last):
  File "C:\TTPassGen-master\ttpassgen\ttpassgen.py", line 6, in <module>
    import click
ModuleNotFoundError: No module named 'click'

**Comment by tp7309** [comment]
If you have any questions, you can always create a new issue^_^
