### ISSUE TITLE
Example given does not work

### ISSUE THREAD

**Issue by adrylek** [tp7309/TTPassGen#4]
I have two lists of words that I want to combine, as given in the last example of the post.
I'm inputting the command: ttpassgen --dictlist in.dict,in2.dict --rule $0[_]?$1 -s "&#160;" out.dict

However, the generated out.dict file is empty aside from a "_" symbol at the start.

What's the issue?

**Comment by tp7309** [comment]
Probably the file encoding of in.dict/in2.dict is not **utf-8**, you can use *--inencoding* option to specify input file encoding(gbk、gb2312、utf8...), or create file with *Notepad++* to ensure that the file encoding is *utf-8*.

The attachment is the in.dict/in2.dict I created.
[sample.zip](https://github.com/tp7309/TTPassGen/files/2747781/sample.zip)
