### ISSUE TITLE
--multiprocessing-fork error

### ISSUE THREAD

**Issue by zdilto** [tp7309/TTPassGen#6]
im using ttpassgen_v1.0.2 windows version but when i run any command the following error will appear and hang endlessly:
```
C:\Users\Youness\Desktop>ttpassgen  -r [123]{2:3}[ab] ttpass.dic
mode: combination rule mode, global_repeat_mode: ?, part_size: 0 Bytes, dictlist: [], rule: [123]{2:3}[ab]
Error: no such option: --multiprocessing-fork
```

anyone have an idea whats cause this error ?

**Comment by tp7309** [comment]
I have updated the windows version, you can try it with the latest v1.0.4 version.

**Comment by zdilto** [comment]
it works now thank you very much
i wonder if there is a way to output to stdout instead of a file

**Comment by tp7309** [comment]
Why not read the dict file after the file is created?
